// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: defiloan/defi_loan.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DefiLoan struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount      string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee         string `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Collaterall string `protobuf:"bytes,4,opt,name=collaterall,proto3" json:"collaterall,omitempty"`
	Deadline    string `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	State       string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Borrower    string `protobuf:"bytes,7,opt,name=borrower,proto3" json:"borrower,omitempty"`
	Lender      string `protobuf:"bytes,8,opt,name=lender,proto3" json:"lender,omitempty"`
}

func (m *DefiLoan) Reset()         { *m = DefiLoan{} }
func (m *DefiLoan) String() string { return proto.CompactTextString(m) }
func (*DefiLoan) ProtoMessage()    {}
func (*DefiLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef27ac9d588f5dd4, []int{0}
}
func (m *DefiLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DefiLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DefiLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DefiLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefiLoan.Merge(m, src)
}
func (m *DefiLoan) XXX_Size() int {
	return m.Size()
}
func (m *DefiLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_DefiLoan.DiscardUnknown(m)
}

var xxx_messageInfo_DefiLoan proto.InternalMessageInfo

func (m *DefiLoan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DefiLoan) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *DefiLoan) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *DefiLoan) GetCollaterall() string {
	if m != nil {
		return m.Collaterall
	}
	return ""
}

func (m *DefiLoan) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

func (m *DefiLoan) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *DefiLoan) GetBorrower() string {
	if m != nil {
		return m.Borrower
	}
	return ""
}

func (m *DefiLoan) GetLender() string {
	if m != nil {
		return m.Lender
	}
	return ""
}

func init() {
	proto.RegisterType((*DefiLoan)(nil), "QuyYeuCode.defiloan.defiloan.DefiLoan")
}

func init() { proto.RegisterFile("defiloan/defi_loan.proto", fileDescriptor_ef27ac9d588f5dd4) }

var fileDescriptor_ef27ac9d588f5dd4 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xb3, 0x69, 0x1b, 0xe3, 0x0a, 0x22, 0x8b, 0xc8, 0x22, 0xb2, 0x04, 0x4f, 0xbd, 0x98,
	0x08, 0xbe, 0x81, 0x7a, 0x12, 0x2f, 0xf6, 0xa6, 0x17, 0xd9, 0x74, 0x27, 0xba, 0xb0, 0xcd, 0x94,
	0xed, 0x06, 0xed, 0x5b, 0xf8, 0x58, 0x1e, 0x3c, 0xf4, 0xe8, 0x51, 0x92, 0x17, 0x91, 0xdd, 0xd8,
	0xd8, 0xdb, 0xff, 0xcd, 0x3f, 0x03, 0xf3, 0xff, 0x94, 0x2b, 0xa8, 0xb4, 0x41, 0x59, 0x17, 0x5e,
	0x3c, 0x7b, 0x95, 0x2f, 0x2d, 0x3a, 0x64, 0x67, 0x0f, 0xcd, 0xfa, 0x11, 0x9a, 0x1b, 0x54, 0x90,
	0x6f, 0x97, 0x06, 0x71, 0xfe, 0x45, 0x68, 0x7a, 0x0b, 0x95, 0xbe, 0x47, 0x59, 0xb3, 0x43, 0x1a,
	0x6b, 0xc5, 0x49, 0x46, 0xa6, 0xe3, 0x59, 0xac, 0x15, 0x3b, 0xa1, 0x89, 0x5c, 0x60, 0x53, 0x3b,
	0x1e, 0x67, 0x64, 0xba, 0x3f, 0xfb, 0x23, 0x76, 0x44, 0x47, 0x15, 0x00, 0x1f, 0x85, 0xa1, 0x97,
	0x2c, 0xa3, 0x07, 0x73, 0x34, 0x46, 0x3a, 0xb0, 0xd2, 0x18, 0x3e, 0x0e, 0xce, 0xee, 0x88, 0x9d,
	0xd2, 0x54, 0x81, 0x54, 0x46, 0xd7, 0xc0, 0x27, 0xc1, 0x1e, 0x98, 0x1d, 0xd3, 0xc9, 0xca, 0x49,
	0x07, 0x3c, 0x09, 0x46, 0x0f, 0xfe, 0xa2, 0x44, 0x6b, 0xf1, 0x0d, 0x2c, 0xdf, 0xeb, 0x2f, 0xb6,
	0xec, 0x3f, 0x33, 0x50, 0x2b, 0xb0, 0x3c, 0xed, 0x3f, 0xeb, 0xe9, 0xfa, 0xee, 0xb3, 0x15, 0x64,
	0xd3, 0x0a, 0xf2, 0xd3, 0x0a, 0xf2, 0xd1, 0x89, 0x68, 0xd3, 0x89, 0xe8, 0xbb, 0x13, 0xd1, 0xd3,
	0xe5, 0x8b, 0x76, 0xaf, 0x4d, 0x99, 0xcf, 0x71, 0x51, 0xfc, 0x37, 0x52, 0xf8, 0xec, 0x17, 0x3e,
	0x7c, 0xf1, 0x5e, 0x0c, 0x15, 0xba, 0xf5, 0x12, 0x56, 0x65, 0x12, 0xfa, 0xbb, 0xfa, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x0f, 0x3e, 0x1f, 0x39, 0x5b, 0x01, 0x00, 0x00,
}

func (m *DefiLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DefiLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DefiLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Lender) > 0 {
		i -= len(m.Lender)
		copy(dAtA[i:], m.Lender)
		i = encodeVarintDefiLoan(dAtA, i, uint64(len(m.Lender)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Borrower) > 0 {
		i -= len(m.Borrower)
		copy(dAtA[i:], m.Borrower)
		i = encodeVarintDefiLoan(dAtA, i, uint64(len(m.Borrower)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintDefiLoan(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Deadline) > 0 {
		i -= len(m.Deadline)
		copy(dAtA[i:], m.Deadline)
		i = encodeVarintDefiLoan(dAtA, i, uint64(len(m.Deadline)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Collaterall) > 0 {
		i -= len(m.Collaterall)
		copy(dAtA[i:], m.Collaterall)
		i = encodeVarintDefiLoan(dAtA, i, uint64(len(m.Collaterall)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintDefiLoan(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintDefiLoan(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintDefiLoan(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDefiLoan(dAtA []byte, offset int, v uint64) int {
	offset -= sovDefiLoan(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DefiLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovDefiLoan(uint64(m.Id))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovDefiLoan(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovDefiLoan(uint64(l))
	}
	l = len(m.Collaterall)
	if l > 0 {
		n += 1 + l + sovDefiLoan(uint64(l))
	}
	l = len(m.Deadline)
	if l > 0 {
		n += 1 + l + sovDefiLoan(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovDefiLoan(uint64(l))
	}
	l = len(m.Borrower)
	if l > 0 {
		n += 1 + l + sovDefiLoan(uint64(l))
	}
	l = len(m.Lender)
	if l > 0 {
		n += 1 + l + sovDefiLoan(uint64(l))
	}
	return n
}

func sovDefiLoan(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDefiLoan(x uint64) (n int) {
	return sovDefiLoan(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DefiLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDefiLoan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DefiLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DefiLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDefiLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDefiLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDefiLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDefiLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collaterall", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDefiLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDefiLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collaterall = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDefiLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDefiLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deadline = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDefiLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDefiLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Borrower", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDefiLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDefiLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Borrower = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDefiLoan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDefiLoan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDefiLoan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDefiLoan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDefiLoan(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDefiLoan
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDefiLoan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDefiLoan
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDefiLoan
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDefiLoan
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDefiLoan        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDefiLoan          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDefiLoan = fmt.Errorf("proto: unexpected end of group")
)
