// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: defiloan/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRequestDefiLoan struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Amount     string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee        string `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Collateral string `protobuf:"bytes,4,opt,name=collateral,proto3" json:"collateral,omitempty"`
	Deadline   string `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (m *MsgRequestDefiLoan) Reset()         { *m = MsgRequestDefiLoan{} }
func (m *MsgRequestDefiLoan) String() string { return proto.CompactTextString(m) }
func (*MsgRequestDefiLoan) ProtoMessage()    {}
func (*MsgRequestDefiLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{0}
}
func (m *MsgRequestDefiLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestDefiLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestDefiLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestDefiLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestDefiLoan.Merge(m, src)
}
func (m *MsgRequestDefiLoan) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestDefiLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestDefiLoan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestDefiLoan proto.InternalMessageInfo

func (m *MsgRequestDefiLoan) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRequestDefiLoan) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgRequestDefiLoan) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *MsgRequestDefiLoan) GetCollateral() string {
	if m != nil {
		return m.Collateral
	}
	return ""
}

func (m *MsgRequestDefiLoan) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

type MsgRequestDefiLoanResponse struct {
}

func (m *MsgRequestDefiLoanResponse) Reset()         { *m = MsgRequestDefiLoanResponse{} }
func (m *MsgRequestDefiLoanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRequestDefiLoanResponse) ProtoMessage()    {}
func (*MsgRequestDefiLoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{1}
}
func (m *MsgRequestDefiLoanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestDefiLoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestDefiLoanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestDefiLoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestDefiLoanResponse.Merge(m, src)
}
func (m *MsgRequestDefiLoanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestDefiLoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestDefiLoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestDefiLoanResponse proto.InternalMessageInfo

type MsgApproveDefiLoan struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgApproveDefiLoan) Reset()         { *m = MsgApproveDefiLoan{} }
func (m *MsgApproveDefiLoan) String() string { return proto.CompactTextString(m) }
func (*MsgApproveDefiLoan) ProtoMessage()    {}
func (*MsgApproveDefiLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{2}
}
func (m *MsgApproveDefiLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApproveDefiLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApproveDefiLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApproveDefiLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApproveDefiLoan.Merge(m, src)
}
func (m *MsgApproveDefiLoan) XXX_Size() int {
	return m.Size()
}
func (m *MsgApproveDefiLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApproveDefiLoan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApproveDefiLoan proto.InternalMessageInfo

func (m *MsgApproveDefiLoan) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgApproveDefiLoan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgApproveDefiLoanResponse struct {
}

func (m *MsgApproveDefiLoanResponse) Reset()         { *m = MsgApproveDefiLoanResponse{} }
func (m *MsgApproveDefiLoanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgApproveDefiLoanResponse) ProtoMessage()    {}
func (*MsgApproveDefiLoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{3}
}
func (m *MsgApproveDefiLoanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgApproveDefiLoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgApproveDefiLoanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgApproveDefiLoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgApproveDefiLoanResponse.Merge(m, src)
}
func (m *MsgApproveDefiLoanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgApproveDefiLoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgApproveDefiLoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgApproveDefiLoanResponse proto.InternalMessageInfo

type MsgRepayDefiLoan struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgRepayDefiLoan) Reset()         { *m = MsgRepayDefiLoan{} }
func (m *MsgRepayDefiLoan) String() string { return proto.CompactTextString(m) }
func (*MsgRepayDefiLoan) ProtoMessage()    {}
func (*MsgRepayDefiLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{4}
}
func (m *MsgRepayDefiLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRepayDefiLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRepayDefiLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRepayDefiLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRepayDefiLoan.Merge(m, src)
}
func (m *MsgRepayDefiLoan) XXX_Size() int {
	return m.Size()
}
func (m *MsgRepayDefiLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRepayDefiLoan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRepayDefiLoan proto.InternalMessageInfo

func (m *MsgRepayDefiLoan) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRepayDefiLoan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgRepayDefiLoanResponse struct {
}

func (m *MsgRepayDefiLoanResponse) Reset()         { *m = MsgRepayDefiLoanResponse{} }
func (m *MsgRepayDefiLoanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRepayDefiLoanResponse) ProtoMessage()    {}
func (*MsgRepayDefiLoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{5}
}
func (m *MsgRepayDefiLoanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRepayDefiLoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRepayDefiLoanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRepayDefiLoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRepayDefiLoanResponse.Merge(m, src)
}
func (m *MsgRepayDefiLoanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRepayDefiLoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRepayDefiLoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRepayDefiLoanResponse proto.InternalMessageInfo

type MsgLiquidateDefiLoan struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgLiquidateDefiLoan) Reset()         { *m = MsgLiquidateDefiLoan{} }
func (m *MsgLiquidateDefiLoan) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidateDefiLoan) ProtoMessage()    {}
func (*MsgLiquidateDefiLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{6}
}
func (m *MsgLiquidateDefiLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiquidateDefiLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiquidateDefiLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiquidateDefiLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidateDefiLoan.Merge(m, src)
}
func (m *MsgLiquidateDefiLoan) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiquidateDefiLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidateDefiLoan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidateDefiLoan proto.InternalMessageInfo

func (m *MsgLiquidateDefiLoan) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgLiquidateDefiLoan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgLiquidateDefiLoanResponse struct {
}

func (m *MsgLiquidateDefiLoanResponse) Reset()         { *m = MsgLiquidateDefiLoanResponse{} }
func (m *MsgLiquidateDefiLoanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidateDefiLoanResponse) ProtoMessage()    {}
func (*MsgLiquidateDefiLoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{7}
}
func (m *MsgLiquidateDefiLoanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLiquidateDefiLoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLiquidateDefiLoanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLiquidateDefiLoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidateDefiLoanResponse.Merge(m, src)
}
func (m *MsgLiquidateDefiLoanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLiquidateDefiLoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidateDefiLoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidateDefiLoanResponse proto.InternalMessageInfo

type MsgCancelDefiLoan struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCancelDefiLoan) Reset()         { *m = MsgCancelDefiLoan{} }
func (m *MsgCancelDefiLoan) String() string { return proto.CompactTextString(m) }
func (*MsgCancelDefiLoan) ProtoMessage()    {}
func (*MsgCancelDefiLoan) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{8}
}
func (m *MsgCancelDefiLoan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelDefiLoan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelDefiLoan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelDefiLoan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelDefiLoan.Merge(m, src)
}
func (m *MsgCancelDefiLoan) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelDefiLoan) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelDefiLoan.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelDefiLoan proto.InternalMessageInfo

func (m *MsgCancelDefiLoan) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCancelDefiLoan) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCancelDefiLoanResponse struct {
}

func (m *MsgCancelDefiLoanResponse) Reset()         { *m = MsgCancelDefiLoanResponse{} }
func (m *MsgCancelDefiLoanResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelDefiLoanResponse) ProtoMessage()    {}
func (*MsgCancelDefiLoanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53df81111addb5b2, []int{9}
}
func (m *MsgCancelDefiLoanResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelDefiLoanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelDefiLoanResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelDefiLoanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelDefiLoanResponse.Merge(m, src)
}
func (m *MsgCancelDefiLoanResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelDefiLoanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelDefiLoanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelDefiLoanResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRequestDefiLoan)(nil), "QuyYeuCode.defiloan.defiloan.MsgRequestDefiLoan")
	proto.RegisterType((*MsgRequestDefiLoanResponse)(nil), "QuyYeuCode.defiloan.defiloan.MsgRequestDefiLoanResponse")
	proto.RegisterType((*MsgApproveDefiLoan)(nil), "QuyYeuCode.defiloan.defiloan.MsgApproveDefiLoan")
	proto.RegisterType((*MsgApproveDefiLoanResponse)(nil), "QuyYeuCode.defiloan.defiloan.MsgApproveDefiLoanResponse")
	proto.RegisterType((*MsgRepayDefiLoan)(nil), "QuyYeuCode.defiloan.defiloan.MsgRepayDefiLoan")
	proto.RegisterType((*MsgRepayDefiLoanResponse)(nil), "QuyYeuCode.defiloan.defiloan.MsgRepayDefiLoanResponse")
	proto.RegisterType((*MsgLiquidateDefiLoan)(nil), "QuyYeuCode.defiloan.defiloan.MsgLiquidateDefiLoan")
	proto.RegisterType((*MsgLiquidateDefiLoanResponse)(nil), "QuyYeuCode.defiloan.defiloan.MsgLiquidateDefiLoanResponse")
	proto.RegisterType((*MsgCancelDefiLoan)(nil), "QuyYeuCode.defiloan.defiloan.MsgCancelDefiLoan")
	proto.RegisterType((*MsgCancelDefiLoanResponse)(nil), "QuyYeuCode.defiloan.defiloan.MsgCancelDefiLoanResponse")
}

func init() { proto.RegisterFile("defiloan/tx.proto", fileDescriptor_53df81111addb5b2) }

var fileDescriptor_53df81111addb5b2 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x8b, 0xd3, 0x40,
	0x1c, 0xc5, 0x9b, 0xb6, 0xae, 0xfa, 0x07, 0xd7, 0xed, 0x20, 0x12, 0x63, 0x19, 0xa4, 0x27, 0x2f,
	0x26, 0xcb, 0x0a, 0x2a, 0xa2, 0xa2, 0xae, 0x27, 0xd9, 0x1c, 0xcc, 0x4d, 0x6f, 0xd3, 0xe4, 0xdf,
	0x38, 0x90, 0x66, 0xd2, 0xcc, 0x44, 0x5b, 0xc1, 0x93, 0x5f, 0xc0, 0x83, 0x1f, 0xca, 0x63, 0x8f,
	0x1e, 0xa5, 0xfd, 0x1e, 0x22, 0x19, 0x9a, 0xb4, 0x4d, 0x74, 0xdb, 0xf4, 0x96, 0x99, 0xff, 0xbc,
	0xdf, 0x7b, 0x61, 0x1e, 0x03, 0xbd, 0x00, 0x47, 0x3c, 0x12, 0x2c, 0x76, 0xd4, 0xd4, 0x4e, 0x52,
	0xa1, 0x04, 0xe9, 0xbf, 0xcb, 0x66, 0xef, 0x31, 0x3b, 0x17, 0x01, 0xda, 0xc5, 0xb4, 0xfc, 0x18,
	0xfc, 0x30, 0x80, 0xb8, 0x32, 0xf4, 0x70, 0x92, 0xa1, 0x54, 0x6f, 0x70, 0xc4, 0x2f, 0x04, 0x8b,
	0x89, 0x09, 0x57, 0xfd, 0x14, 0x99, 0x12, 0xa9, 0x69, 0xdc, 0x33, 0xee, 0x5f, 0xf7, 0x8a, 0x25,
	0xb9, 0x0d, 0x47, 0x6c, 0x2c, 0xb2, 0x58, 0x99, 0x6d, 0x3d, 0x58, 0xad, 0xc8, 0x09, 0x74, 0x46,
	0x88, 0x66, 0x47, 0x6f, 0xe6, 0x9f, 0x84, 0x02, 0xf8, 0x22, 0x8a, 0x98, 0xc2, 0x94, 0x45, 0x66,
	0x57, 0x0f, 0x36, 0x76, 0x88, 0x05, 0xd7, 0x02, 0x64, 0x41, 0xc4, 0x63, 0x34, 0xaf, 0xe8, 0x69,
	0xb9, 0x1e, 0xf4, 0xc1, 0xaa, 0xa7, 0xf2, 0x50, 0x26, 0x22, 0x96, 0x38, 0x78, 0xa1, 0x33, 0xbf,
	0x4a, 0x92, 0x54, 0x7c, 0xc2, 0x3d, 0x32, 0x1f, 0x43, 0x9b, 0x07, 0x3a, 0x6f, 0xd7, 0x6b, 0xf3,
	0x60, 0x45, 0xaf, 0xe8, 0x4b, 0xfa, 0x33, 0x38, 0xd1, 0xde, 0x09, 0x9b, 0x1d, 0xc0, 0xb6, 0xc0,
	0xac, 0xaa, 0x4b, 0xf2, 0x4b, 0xb8, 0xe5, 0xca, 0xf0, 0x82, 0x4f, 0x32, 0x1e, 0x30, 0x75, 0x48,
	0x72, 0x0a, 0xfd, 0x7f, 0x11, 0x4a, 0x87, 0xe7, 0xd0, 0x73, 0x65, 0x78, 0xce, 0x62, 0x1f, 0xa3,
	0x03, 0xf0, 0x77, 0xe1, 0x4e, 0x4d, 0x5e, 0xb0, 0xcf, 0xfe, 0x74, 0xa1, 0xe3, 0xca, 0x90, 0x7c,
	0x85, 0x9b, 0xd5, 0xba, 0x9c, 0xda, 0x97, 0x95, 0xcc, 0xae, 0x5f, 0xa5, 0xf5, 0xa4, 0xa9, 0xa2,
	0x88, 0x91, 0xdb, 0x57, 0x6f, 0x7e, 0xb7, 0x7d, 0x45, 0xb1, 0x87, 0xfd, 0x7f, 0xda, 0x41, 0x3e,
	0xc3, 0x8d, 0xed, 0x6a, 0xd8, 0x7b, 0xfc, 0xc9, 0xc6, 0x79, 0xeb, 0x51, 0xb3, 0xf3, 0xa5, 0xf1,
	0x37, 0x03, 0x7a, 0xf5, 0xea, 0x9c, 0xed, 0xa4, 0xd5, 0x34, 0xd6, 0xd3, 0xe6, 0x9a, 0x32, 0xc5,
	0x17, 0x38, 0xae, 0xb4, 0xcb, 0xd9, 0x49, 0xdb, 0x16, 0x58, 0x8f, 0x1b, 0x0a, 0x0a, 0xef, 0xd7,
	0x6f, 0x7f, 0x2e, 0xa8, 0x31, 0x5f, 0x50, 0xe3, 0xf7, 0x82, 0x1a, 0xdf, 0x97, 0xb4, 0x35, 0x5f,
	0xd2, 0xd6, 0xaf, 0x25, 0x6d, 0x7d, 0x38, 0x0d, 0xb9, 0xfa, 0x98, 0x0d, 0x6d, 0x5f, 0x8c, 0x9d,
	0x35, 0xdc, 0xc9, 0x09, 0x0f, 0x72, 0x84, 0x33, 0x75, 0xd6, 0x0f, 0xe3, 0x2c, 0x41, 0x39, 0x3c,
	0xd2, 0x8f, 0xe3, 0xc3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0xf3, 0x11, 0xe3, 0x31, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RequestDefiLoan(ctx context.Context, in *MsgRequestDefiLoan, opts ...grpc.CallOption) (*MsgRequestDefiLoanResponse, error)
	ApproveDefiLoan(ctx context.Context, in *MsgApproveDefiLoan, opts ...grpc.CallOption) (*MsgApproveDefiLoanResponse, error)
	RepayDefiLoan(ctx context.Context, in *MsgRepayDefiLoan, opts ...grpc.CallOption) (*MsgRepayDefiLoanResponse, error)
	LiquidateDefiLoan(ctx context.Context, in *MsgLiquidateDefiLoan, opts ...grpc.CallOption) (*MsgLiquidateDefiLoanResponse, error)
	CancelDefiLoan(ctx context.Context, in *MsgCancelDefiLoan, opts ...grpc.CallOption) (*MsgCancelDefiLoanResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RequestDefiLoan(ctx context.Context, in *MsgRequestDefiLoan, opts ...grpc.CallOption) (*MsgRequestDefiLoanResponse, error) {
	out := new(MsgRequestDefiLoanResponse)
	err := c.cc.Invoke(ctx, "/QuyYeuCode.defiloan.defiloan.Msg/RequestDefiLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ApproveDefiLoan(ctx context.Context, in *MsgApproveDefiLoan, opts ...grpc.CallOption) (*MsgApproveDefiLoanResponse, error) {
	out := new(MsgApproveDefiLoanResponse)
	err := c.cc.Invoke(ctx, "/QuyYeuCode.defiloan.defiloan.Msg/ApproveDefiLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RepayDefiLoan(ctx context.Context, in *MsgRepayDefiLoan, opts ...grpc.CallOption) (*MsgRepayDefiLoanResponse, error) {
	out := new(MsgRepayDefiLoanResponse)
	err := c.cc.Invoke(ctx, "/QuyYeuCode.defiloan.defiloan.Msg/RepayDefiLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LiquidateDefiLoan(ctx context.Context, in *MsgLiquidateDefiLoan, opts ...grpc.CallOption) (*MsgLiquidateDefiLoanResponse, error) {
	out := new(MsgLiquidateDefiLoanResponse)
	err := c.cc.Invoke(ctx, "/QuyYeuCode.defiloan.defiloan.Msg/LiquidateDefiLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelDefiLoan(ctx context.Context, in *MsgCancelDefiLoan, opts ...grpc.CallOption) (*MsgCancelDefiLoanResponse, error) {
	out := new(MsgCancelDefiLoanResponse)
	err := c.cc.Invoke(ctx, "/QuyYeuCode.defiloan.defiloan.Msg/CancelDefiLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RequestDefiLoan(context.Context, *MsgRequestDefiLoan) (*MsgRequestDefiLoanResponse, error)
	ApproveDefiLoan(context.Context, *MsgApproveDefiLoan) (*MsgApproveDefiLoanResponse, error)
	RepayDefiLoan(context.Context, *MsgRepayDefiLoan) (*MsgRepayDefiLoanResponse, error)
	LiquidateDefiLoan(context.Context, *MsgLiquidateDefiLoan) (*MsgLiquidateDefiLoanResponse, error)
	CancelDefiLoan(context.Context, *MsgCancelDefiLoan) (*MsgCancelDefiLoanResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RequestDefiLoan(ctx context.Context, req *MsgRequestDefiLoan) (*MsgRequestDefiLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDefiLoan not implemented")
}
func (*UnimplementedMsgServer) ApproveDefiLoan(ctx context.Context, req *MsgApproveDefiLoan) (*MsgApproveDefiLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveDefiLoan not implemented")
}
func (*UnimplementedMsgServer) RepayDefiLoan(ctx context.Context, req *MsgRepayDefiLoan) (*MsgRepayDefiLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepayDefiLoan not implemented")
}
func (*UnimplementedMsgServer) LiquidateDefiLoan(ctx context.Context, req *MsgLiquidateDefiLoan) (*MsgLiquidateDefiLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LiquidateDefiLoan not implemented")
}
func (*UnimplementedMsgServer) CancelDefiLoan(ctx context.Context, req *MsgCancelDefiLoan) (*MsgCancelDefiLoanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelDefiLoan not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RequestDefiLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestDefiLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestDefiLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QuyYeuCode.defiloan.defiloan.Msg/RequestDefiLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestDefiLoan(ctx, req.(*MsgRequestDefiLoan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ApproveDefiLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApproveDefiLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApproveDefiLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QuyYeuCode.defiloan.defiloan.Msg/ApproveDefiLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApproveDefiLoan(ctx, req.(*MsgApproveDefiLoan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RepayDefiLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRepayDefiLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RepayDefiLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QuyYeuCode.defiloan.defiloan.Msg/RepayDefiLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RepayDefiLoan(ctx, req.(*MsgRepayDefiLoan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LiquidateDefiLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLiquidateDefiLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LiquidateDefiLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QuyYeuCode.defiloan.defiloan.Msg/LiquidateDefiLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LiquidateDefiLoan(ctx, req.(*MsgLiquidateDefiLoan))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelDefiLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelDefiLoan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelDefiLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/QuyYeuCode.defiloan.defiloan.Msg/CancelDefiLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelDefiLoan(ctx, req.(*MsgCancelDefiLoan))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "QuyYeuCode.defiloan.defiloan.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestDefiLoan",
			Handler:    _Msg_RequestDefiLoan_Handler,
		},
		{
			MethodName: "ApproveDefiLoan",
			Handler:    _Msg_ApproveDefiLoan_Handler,
		},
		{
			MethodName: "RepayDefiLoan",
			Handler:    _Msg_RepayDefiLoan_Handler,
		},
		{
			MethodName: "LiquidateDefiLoan",
			Handler:    _Msg_LiquidateDefiLoan_Handler,
		},
		{
			MethodName: "CancelDefiLoan",
			Handler:    _Msg_CancelDefiLoan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defiloan/tx.proto",
}

func (m *MsgRequestDefiLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestDefiLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestDefiLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Deadline) > 0 {
		i -= len(m.Deadline)
		copy(dAtA[i:], m.Deadline)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Deadline)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Collateral) > 0 {
		i -= len(m.Collateral)
		copy(dAtA[i:], m.Collateral)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Collateral)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestDefiLoanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestDefiLoanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestDefiLoanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgApproveDefiLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApproveDefiLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApproveDefiLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgApproveDefiLoanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgApproveDefiLoanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgApproveDefiLoanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRepayDefiLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRepayDefiLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRepayDefiLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRepayDefiLoanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRepayDefiLoanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRepayDefiLoanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgLiquidateDefiLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiquidateDefiLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiquidateDefiLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLiquidateDefiLoanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLiquidateDefiLoanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLiquidateDefiLoanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelDefiLoan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelDefiLoan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelDefiLoan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelDefiLoanResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelDefiLoanResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelDefiLoanResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRequestDefiLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Collateral)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Deadline)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRequestDefiLoanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgApproveDefiLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgApproveDefiLoanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRepayDefiLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgRepayDefiLoanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgLiquidateDefiLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgLiquidateDefiLoanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelDefiLoan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCancelDefiLoanResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRequestDefiLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestDefiLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestDefiLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collateral = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deadline = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestDefiLoanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestDefiLoanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestDefiLoanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApproveDefiLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApproveDefiLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApproveDefiLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgApproveDefiLoanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgApproveDefiLoanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgApproveDefiLoanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRepayDefiLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRepayDefiLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRepayDefiLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRepayDefiLoanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRepayDefiLoanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRepayDefiLoanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLiquidateDefiLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiquidateDefiLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiquidateDefiLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLiquidateDefiLoanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLiquidateDefiLoanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLiquidateDefiLoanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelDefiLoan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelDefiLoan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelDefiLoan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelDefiLoanResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelDefiLoanResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelDefiLoanResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
